export type ScreenKey =
  | 'dashboard'
  | 'systemAdmins'
  | 'systemUserPermissions'
  | 'systemGroupPermissions'
  | 'systemMenuPermissions'
  | 'systemMenus'
  | 'systemCodes'
  | 'facilityAccessRealtime'
  | 'facilityAccessHistory'
  | 'facilityEnvironmentRealtime'
  | 'facilityEnvironmentHistory'
  | 'facilityCctv'
  | 'facilityDataPermissions'
  | 'equipmentInfo'
  | 'equipmentStatus'
  | 'equipmentOperationRate'
  | 'equipmentMaintenance'
  | 'equipmentAlerts'
  | 'masterWorkplaces'
  | 'masterFactories'
  | 'masterDepartments'
  | 'masterClients'
  | 'masterItems'
  | 'masterWarehouses'
  | 'masterBom'
  | 'salesOrders'
  | 'salesOrderBacklog'
  | 'salesOrderMonthly'
  | 'salesDeliveries'
  | 'salesPerformance'
  | 'productionWorkOrders'
  | 'productionResults'
  | 'productionResultStatus'
  | 'materialReceipts'
  | 'materialShipments'
  | 'materialIssues'
  | 'materialReturns'
  | 'materialStocks'
  | 'materialStockAdjustments'
  | 'qualityInspectionStandards'
  | 'qualityWorkStandards'
  | 'qualityInspections'
  | 'qualityInspectionChanges'
  | 'qualityDefects'
  | 'qualityDefectTrends'
  | 'dataList'
  | 'dataProcess'
  | 'dataVisualization'
  | 'messageSend'
  | 'messageHistory'

export type StatusTone = 'good' | 'warn' | 'danger' | 'info' | 'muted'

export type MenuGroup = {
  title: string
  items: Array<{ key: ScreenKey; label: string }>
}
