import type { ComponentType, SVGProps } from 'react'

export type ScreenKey =
  | 'dashboard'
  | 'systemUsers'
  | 'systemUserPermissions'
  | 'systemAccessLogs'
  | 'facilityAccessManage'
  | 'facilityAccessRealtime'
  | 'facilityAccessHistory'
  | 'facilityEnvironmentRealtime'
  | 'facilityEnvironmentHistory'
  | 'facilityCctv'
  | 'facilityDataManage'
  | 'masterFactories'
  | 'masterEquipment'
  | 'masterProcesses'
  | 'masterItems'
  | 'masterDefects'
  | 'equipmentList'
  | 'equipmentOperationStatus'
  | 'equipmentOperationHistory'
  | 'equipmentAlarmSystem'
  | 'equipmentRepairHistory'
  | 'seedInventoryStatus'
  | 'seedReportReturnManage'
  | 'seedInventoryManage'
  | 'foodWorkOrders'
  | 'foodProductionResults'
  | 'foodProductionStatus'
  | 'foodLotManage'
  | 'foodInspectionStandards'
  | 'foodDefectManage'
  | 'foodDefectStatus'
  | 'inpiInventoryStatus'
  | 'inpiInventoryManage'
  | 'inpiWorkOrders'
  | 'inpiProductionResults'
  | 'inpiProductionStatus'
  | 'inpiLotManage'
  | 'inpiInspectionStandards'
  | 'inpiDefectManage'
  | 'inpiDefectStatus'

export type StatusTone = 'good' | 'warn' | 'danger' | 'info' | 'muted' | 'limits'

export interface MenuGroup {
  title: string
  icon: ComponentType<SVGProps<SVGSVGElement>>
  items: { key: ScreenKey; label: string }[]
}
